# Nampy Basic Assignment

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [5]:
list_ = [ 1 , '2' , 'Shashank' , [1,2] , 'shambhu' ]

In [9]:
for item in list_:
    print (type(item))


<class 'int'>
<class 'str'>
<class 'str'>
<class 'list'>
<class 'str'>


In [12]:
l = [1,2,45,23,34]
arra_list = np.array(l)

In [13]:
for item in arra_list:
    print (type(item))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [15]:
array_list = np.array(object = l, dtype = int)

In [16]:
for item in l:
    print (type(item))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [17]:
for item in array_list:
    print (type(item))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


 Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [18]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.


In [23]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [24]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])